apiVersion: v1
kind: Secret
metadata:
  name: kube-fundamentals-db-credentials
  namespace: kubernetes-fundamentals
type: Opaque
data:
  # Values must be base64 encoded
  password: TXlTZWN1cmVQQHNzdzByZCE=
  connection-string: U2VydmVyPXBvc3RncmVzO0RhdGFiYXNlPW15ZGI7VXNlciBJZD1hZG1pbjtQYXNzd29yZD1NeVNlY3VyZVBAc3N3MHJkIQ==